---
- name: Копирование локальных файлов zabbix-agent
  synchronize:
    src: files/zabbix-packages
    dest: /tmp
    mode: push

- name: Локальная установка zabbix-agent
  shell: dpkg -i /tmp/zabbix-packages/*.deb

- name: Конфигурирование zabbix-agent
  template:
    src: zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: 
    - Перезапуск zabbix-agent

