---
- name: Перезапуск zabbix-server
  service:
    name: zabbix-server
    state: restarted
    enabled: yes

- name: Перезапуск Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes