---
- name: Add repository Elastic
  apt_repository:
    repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
    state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Copy configuration file Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: '0644'
  notify: 
    - Restart elasticsearch


