---
- name: Добавление репозитория Elastic
  apt_repository:
    repo: 'deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/7/ stable main'
    state: present

- name: Установка Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Копирование конфигурации для  Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: '0644'
  notify: 
    - Перезапуск elasticsearch


